name: Test `wasm_runtime.so`

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  $APACHE_PATH: './Apache_v2.4'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout Apache HTTP Server repository
        uses: actions/checkout@v3
        with:
          repository: apache/httpd
          path: $APACHE_PATH
      

# jobs:
#   test:
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [ubuntu-latest, windows-latest, macos-latest]
#     runs-on: ${{ matrix.os }}
#     steps:
#     - uses: actions/checkout@v3
#     - name: Build
#       working-directory: ./wasm_runtime
#       run: cargo build --verbose
#     - name: Run tests
#       working-directory: ./wasm_runtime
#       run: cargo test --verbose
